In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# Abrindo arquivo com panda
data_xlsx = pd.read_excel('chegadas_2016.xlsx')
data_xlsx[0:10]

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Terrestre,2,2016,janeiro,1,1
1,África,1,Angola,6,Acre,1,Terrestre,2,2016,janeiro,1,0
2,África,1,Cabo Verde,35,Acre,1,Terrestre,2,2016,janeiro,1,0
3,África,1,Egito,60,Acre,1,Terrestre,2,2016,janeiro,1,2
4,África,1,Gana,77,Acre,1,Terrestre,2,2016,janeiro,1,0
5,África,1,Marrocos,143,Acre,1,Terrestre,2,2016,janeiro,1,0
6,África,1,Moçambique,151,Acre,1,Terrestre,2,2016,janeiro,1,0
7,África,1,Nigéria,162,Acre,1,Terrestre,2,2016,janeiro,1,0
8,África,1,Quênia,180,Acre,1,Terrestre,2,2016,janeiro,1,0
9,África,1,Tunísia,228,Acre,1,Terrestre,2,2016,janeiro,1,0

In [25]:
data = data_xlsx[data_xlsx.Chegadas != 0] # sem chegadas, não interessa
data

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
0,África,1,África do Sul,2,Acre,1,Terrestre,2,2016,janeiro,1,1
3,África,1,Egito,60,Acre,1,Terrestre,2,2016,janeiro,1,2
11,América Central e Caribe,2,Costa Rica,53,Acre,1,Terrestre,2,2016,janeiro,1,2
12,América Central e Caribe,2,Cuba,55,Acre,1,Terrestre,2,2016,janeiro,1,3
22,América do Norte,3,Canadá,38,Acre,1,Terrestre,2,2016,janeiro,1,1
23,América do Norte,3,Estados Unidos,68,Acre,1,Terrestre,2,2016,janeiro,1,4
24,América do Norte,3,México,148,Acre,1,Terrestre,2,2016,janeiro,1,5
25,América do Sul,4,Argentina,11,Acre,1,Terrestre,2,2016,janeiro,1,14
26,América do Sul,4,Bolívia,26,Acre,1,Terrestre,2,2016,janeiro,1,1110
27,América do Sul,4,Chile,42,Acre,1,Terrestre,2,2016,janeiro,1,10
28,América do Sul,4,Colômbia,48,Acre,1,Terrestre,2,2016,janeiro,1,20
29,América do Sul,4,Equador,63,Acre,1,Terrestre,2,2016,janeiro,1,8
33,América do Sul,4,Peru,174,Acre,1,Terrestre,2,2016,janeiro,1,1568
35,América do Sul,4,Uruguai,234,Acre,1,Terrestre,2,2016,janeiro,1,1
36,América do Sul,4,Venezuela,238,Acre,1,Terrestre,2,2016,janeiro,1,5
42,Ásia,5,Filipinas,72,Acre,1,Terrestre,2,2016,janeiro,1,1
46,Ásia,5,Israel,119,Acre,1,Terrestre,2,2016,janeiro,1,2
47,Ásia,5,Japão,122,Acre,1,Terrestre,2,2016,janeiro,1,2
53,Ásia,5,Tailândia,220,Acre,1,Terrestre,2,2016,janeiro,1,2
56,Europa,6,Alemanha,4,Acre,1,Terrestre,2,2016,janeiro,1,4
57,Europa,6,Áustria,15,Acre,1,Terrestre,2,2016,janeiro,1,2
58,Europa,6,Bélgica,21,Acre,1,Terrestre,2,2016,janeiro,1,1
64,Europa,6,Espanha,67,Acre,1,Terrestre,2,2016,janeiro,1,8
65,Europa,6,Estônia,69,Acre,1,Terrestre,2,2016,janeiro,1,1
66,Europa,6,Finlândia,73,Acre,1,Terrestre,2,2016,janeiro,1,2
67,Europa,6,França,74,Acre,1,Terrestre,2,2016,janeiro,1,10
69,Europa,6,Holanda,92,Acre,1,Terrestre,2,2016,janeiro,1,3
71,Europa,6,Irlanda,117,Acre,1,Terrestre,2,2016,janeiro,1,1
72,Europa,6,Itália,120,Acre,1,Terrestre,2,2016,janeiro,1,10
77,Europa,6,Polônia,177,Acre,1,Terrestre,2,2016,janeiro,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
44403,Ásia,5,Filipinas,72,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44404,Ásia,5,Índia,113,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,2
44417,Europa,6,Alemanha,4,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,4
44418,Europa,6,Áustria,15,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,2
44421,Europa,6,Croácia,54,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44428,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,6
44429,Europa,6,Grécia,81,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44433,Europa,6,Itália,120,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,2
44440,Europa,6,Reino Unido,182,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44442,Europa,6,Romênia,188,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44445,Europa,6,Suécia,215,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44446,Europa,6,Suíça,216,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,3
44449,Europa,6,Outros países,998,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,13
44475,América Central e Caribe,2,Outros países,998,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44479,América do Sul,4,Argentina,11,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44481,América do Sul,4,Chile,42,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44496,Ásia,5,Filipinas,72,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,13
44497,Ásia,5,Índia,113,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44510,Europa,6,Alemanha,4,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,3
44515,Europa,6,Dinamarca,57,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44521,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,11
44522,Europa,6,Grécia,81,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44533,Europa,6,Reino Unido,182,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44539,Europa,6,Suíça,216,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,2
44569,América do Norte,3,Canadá,38,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,1
44572,América do Sul,4,Argentina,11,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,2
44614,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,7
44615,Europa,6,Grécia,81,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,1
44625,Europa,6,Portugal,179,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,1
44629,Europa,6,Rússia,190,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,3

In [26]:
data[data.Continente.str.contains('Europa')]

,Continente,cod continente,País,cod pais,UF,cod uf,Via,cod via,ano,Mês,cod mes,Chegadas
56,Europa,6,Alemanha,4,Acre,1,Terrestre,2,2016,janeiro,1,4
57,Europa,6,Áustria,15,Acre,1,Terrestre,2,2016,janeiro,1,2
58,Europa,6,Bélgica,21,Acre,1,Terrestre,2,2016,janeiro,1,1
64,Europa,6,Espanha,67,Acre,1,Terrestre,2,2016,janeiro,1,8
65,Europa,6,Estônia,69,Acre,1,Terrestre,2,2016,janeiro,1,1
66,Europa,6,Finlândia,73,Acre,1,Terrestre,2,2016,janeiro,1,2
67,Europa,6,França,74,Acre,1,Terrestre,2,2016,janeiro,1,10
69,Europa,6,Holanda,92,Acre,1,Terrestre,2,2016,janeiro,1,3
71,Europa,6,Irlanda,117,Acre,1,Terrestre,2,2016,janeiro,1,1
72,Europa,6,Itália,120,Acre,1,Terrestre,2,2016,janeiro,1,10
77,Europa,6,Polônia,177,Acre,1,Terrestre,2,2016,janeiro,1,2
78,Europa,6,Portugal,179,Acre,1,Terrestre,2,2016,janeiro,1,7
79,Europa,6,Reino Unido,182,Acre,1,Terrestre,2,2016,janeiro,1,6
81,Europa,6,Romênia,188,Acre,1,Terrestre,2,2016,janeiro,1,1
82,Europa,6,Rússia,190,Acre,1,Terrestre,2,2016,janeiro,1,1
84,Europa,6,Suécia,215,Acre,1,Terrestre,2,2016,janeiro,1,3
87,Europa,6,Ucrânia,232,Acre,1,Terrestre,2,2016,janeiro,1,2
149,Europa,6,Alemanha,4,Acre,1,Terrestre,2,2016,fevereiro,2,15
150,Europa,6,Áustria,15,Acre,1,Terrestre,2,2016,fevereiro,2,1
151,Europa,6,Bélgica,21,Acre,1,Terrestre,2,2016,fevereiro,2,3
152,Europa,6,Bulgária,31,Acre,1,Terrestre,2,2016,fevereiro,2,1
157,Europa,6,Espanha,67,Acre,1,Terrestre,2,2016,fevereiro,2,3
159,Europa,6,Finlândia,73,Acre,1,Terrestre,2,2016,fevereiro,2,3
160,Europa,6,França,74,Acre,1,Terrestre,2,2016,fevereiro,2,9
161,Europa,6,Grécia,81,Acre,1,Terrestre,2,2016,fevereiro,2,1
162,Europa,6,Holanda,92,Acre,1,Terrestre,2,2016,fevereiro,2,1
164,Europa,6,Irlanda,117,Acre,1,Terrestre,2,2016,fevereiro,2,1
165,Europa,6,Itália,120,Acre,1,Terrestre,2,2016,fevereiro,2,5
169,Europa,6,Noruega,164,Acre,1,Terrestre,2,2016,fevereiro,2,1
170,Europa,6,Polônia,177,Acre,1,Terrestre,2,2016,fevereiro,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...
44252,Europa,6,Polônia,177,Outras Unidades da Federação,99,Marítima,3,2016,agosto,8,1
44260,Europa,6,Suíça,216,Outras Unidades da Federação,99,Marítima,3,2016,agosto,8,1
44324,Europa,6,Alemanha,4,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,6
44326,Europa,6,Bélgica,21,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,2
44332,Europa,6,Espanha,67,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,1
44335,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,4
44340,Europa,6,Itália,120,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,1
44352,Europa,6,Suécia,215,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,1
44353,Europa,6,Suíça,216,Outras Unidades da Federação,99,Marítima,3,2016,setembro,9,2
44417,Europa,6,Alemanha,4,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,4
44418,Europa,6,Áustria,15,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,2
44421,Europa,6,Croácia,54,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44428,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,6
44429,Europa,6,Grécia,81,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44433,Europa,6,Itália,120,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,2
44440,Europa,6,Reino Unido,182,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44442,Europa,6,Romênia,188,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44445,Europa,6,Suécia,215,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,1
44446,Europa,6,Suíça,216,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,3
44449,Europa,6,Outros países,998,Outras Unidades da Federação,99,Marítima,3,2016,outubro,10,13
44510,Europa,6,Alemanha,4,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,3
44515,Europa,6,Dinamarca,57,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44521,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,11
44522,Europa,6,Grécia,81,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44533,Europa,6,Reino Unido,182,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,1
44539,Europa,6,Suíça,216,Outras Unidades da Federação,99,Marítima,3,2016,novembro,11,2
44614,Europa,6,França,74,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,7
44615,Europa,6,Grécia,81,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,1
44625,Europa,6,Portugal,179,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,1
44629,Europa,6,Rússia,190,Outras Unidades da Federação,99,Marítima,3,2016,dezembro,12,3